### ISSUE TITLE
Formatting a citation throws an exception

### ISSUE THREAD

**Issue by rdmpage** [pensoft/refindit#4]
I've grabbed the current repository and am running it locally (Mac OS X 10.10.5 , node v0.12.4). If I try and format a citation I invariably get an exception rather than a formatted citation:
```
/Users/rpage/Development/refindit/format/node_modules/jsdom/lib/jsdom/level1/core.js:412 set nodeName() { throw new core.DOMException();}, ^ SyntaxError: Unexpected token ) at exports.runInThisContext (vm.js:73:16) at Module._compile (module.js:443:25) at Object.Module._extensions..js (module.js:478:10) at Module.load (module.js:355:32) at Function.Module._load (module.js:310:12) at Module.require (module.js:365:17) at require (module.js:384:17) at Object. (/Users/rpage/Development/refindit/format/node_modules/jsdom/lib/jsdom/level2/core.js:1:94) at Module._compile (module.js:460:26) at Object.Module._extensions..js (module.js:478:10)
```

I've also created a Dockerised version of refindit and I get the same error. Is the production code in use at http://refindit.org the same as what is in this repository?

**Comment by Biserkov** [comment]
I'll look into it later today.

**Comment by Biserkov** [comment]
ReFindit was written on Node.js version 0.10.x. It seems that version 0.12.4 added some new JavaScript syntax around setters and one of the dependencies is incompatible with it.

As a short-term workaround you can use Node.js v.0.10.x. My [personal fork](https://github.com/Biserkov/refindit) has a "Deploy to Heroku" button that is super easy to use. It also has a package.json which specifies the Node.js version required.

Long-term, the dependencies need to be updated (if possible) to a version compatible with the latest Node.js (6.10 as of this writing).

**Comment by rdmpage** [comment]
@Biserkov I found another bug which I've fixed, see https://github.com/rdmpage/refindit/issues/2 Turns out the fix is pretty trivial, and I now have a dockerised version of refindit that seems to work. There's a live version here: https://refindit.sloppy.zone
